// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTMRi8h-ULQ2yAuVKeNxIjjyl46IlAvio',
    appId: '1:836550594185:web:8d569baf6187aa827b4058',
    messagingSenderId: '836550594185',
    projectId: 'city-guide-628d2',
    authDomain: 'city-guide-628d2.firebaseapp.com',
    storageBucket: 'city-guide-628d2.appspot.com',
    measurementId: 'G-44CGFVVESS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFGUJGGaW3pKQ_WkszytuZq5VDDWzLoMA',
    appId: '1:836550594185:android:4dc1d87f02e906467b4058',
    messagingSenderId: '836550594185',
    projectId: 'city-guide-628d2',
    storageBucket: 'city-guide-628d2.appspot.com',
  );

}